apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
stringData:
  mariadb-root-password: myrootpassword
  mariadb-user: nextcloud
  mariadb-password: nextcloudpassword
  mariadb-database: nextcloud

