apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker2        
      containers:
      - name: mariadb
        image: mariadb:11-ubi
        ports:
          - containerPort: 3306
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-db-secret
                key: mariadb-root-password
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: nextcloud-db-secret
                key: mariadb-database
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: nextcloud-db-secret
                key: mariadb-user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-db-secret
                key: mariadb-password
        volumeMounts:
          - name: mariadb-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
