apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
# change the hostPath to nfs 
  nfs:
    path: /data/nfs/nextcloud/mariadb
    server: 192.168.0.201
#  hostPath:
#    path: /mnt/data/mariadb
