apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain

# change the hostPath to nfs
  nfs:
    path: /data/nfs/nextcloud/nextcloud
    server: 192.168.0.201  
#  hostPath:
#    path: /mnt/data/nextcloud

