apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-http
  namespace: monitoring
  labels:
    release: kube-prometheus-stack 
spec:
  jobName: blackbox-http
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://dennisapp.duckdns.org
        - https://drive-nextcloud.duckdns.org
        - https://homepage-homelab.duckdns.org
